// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutoBlurButton: typeof import('./src/components/AutoBlurButton.vue')['default']
    DialogAction: typeof import('./src/components/DialogPanel.vue')['default']
    DialogHistoryEventPanel: typeof import('./src/components/DialogPanel.vue')['default']
    DialogPanel: typeof import('./src/components/DialogPanel.vue')['default']
    Effects: typeof import('./src/components/Effects.vue')['default']
    EffectTags: typeof import('./src/components/EffectTags.vue')['default']
    EventInteractiveItem: typeof import('./src/components/LatestPanel.vue')['default']
    EventItem: typeof import('./src/components/HistoryEventPanel.vue')['default']
    EventList: typeof import('./src/components/EventList.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    GameOverPanel: typeof import('./src/components/GameOverPanel.vue')['default']
    HistoryEventList: typeof import('./src/components/EventList.vue')['default']
    HistoryEventListItem: typeof import('./src/components/HistoryEventPanel.vue')['default']
    HistoryEventPanel: typeof import('./src/components/HistoryEventPanel.vue')['default']
    HistoryEventPanelNoHeader: typeof import('./src/components/DialogPanel.vue')['default']
    HistoryEvents: typeof import('./src/components/EventList.vue')['default']
    InteractiveButton: typeof import('./src/components/InteractiveButton.vue')['default']
    InteractiveEventPanel: typeof import('./src/components/LatestPanel.vue')['default']
    InteractivePanel: typeof import('./src/components/InteractivePanel.vue')['default']
    LatestPanel: typeof import('./src/components/LatestPanel.vue')['default']
    LoadingPanel: typeof import('./src/components/LoadingPanel.vue')['default']
    NAffix: typeof import('naive-ui')['NAffix']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NH1: typeof import('naive-ui')['NH1']
    NH3: typeof import('naive-ui')['NH3']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NP: typeof import('naive-ui')['NP']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    PropertyPanel: typeof import('./src/components/PropertyPanel.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
